use reinhardt_migrations::prelude::*;
pub fn migration() -> Migration {
	Migration {
		app_label: "auto".to_string(),
		name: "auto_migration_20251129_230034".to_string(),
		operations: vec![
			Operation::CreateTable {
				name: "user".to_string(),
				columns: vec![
					ColumnDefinition {
						name: "email".to_string(),
						type_definition: "CharField".to_string(),
						not_null: true,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
						max_length: None,
					},
					ColumnDefinition {
						name: "created_at".to_string(),
						type_definition: "DateTimeField".to_string(),
						not_null: true,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
						max_length: None,
					},
					ColumnDefinition {
						name: "id".to_string(),
						type_definition: "BigIntegerField".to_string(),
						not_null: true,
						unique: false,
						primary_key: true,
						auto_increment: false,
						default: None,
						max_length: None,
					},
					ColumnDefinition {
						name: "name".to_string(),
						type_definition: "CharField".to_string(),
						not_null: true,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
						max_length: None,
					},
				],
				constraints: vec![],
			},
			Operation::CreateTable {
				name: "todo".to_string(),
				columns: vec![
					ColumnDefinition {
						name: "updated_at".to_string(),
						type_definition: "DateTimeField".to_string(),
						not_null: true,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
						max_length: None,
					},
					ColumnDefinition {
						name: "title".to_string(),
						type_definition: "CharField".to_string(),
						not_null: true,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
						max_length: None,
					},
					ColumnDefinition {
						name: "id".to_string(),
						type_definition: "BigIntegerField".to_string(),
						not_null: true,
						unique: false,
						primary_key: true,
						auto_increment: false,
						default: None,
						max_length: None,
					},
					ColumnDefinition {
						name: "created_at".to_string(),
						type_definition: "DateTimeField".to_string(),
						not_null: true,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
						max_length: None,
					},
					ColumnDefinition {
						name: "completed".to_string(),
						type_definition: "BooleanField".to_string(),
						not_null: true,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
						max_length: None,
					},
					ColumnDefinition {
						name: "description".to_string(),
						type_definition: "CharField".to_string(),
						not_null: true,
						unique: false,
						primary_key: false,
						auto_increment: false,
						default: None,
						max_length: None,
					},
				],
				constraints: vec![],
			},
		],
		dependencies: vec![],
		atomic: true,
		replaces: vec![],
	}
}
